# Generated by Django 4.2.14 on 2024-09-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('amount', models.IntegerField()),
                ('account_number', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=64)),
                ('call_number', models.CharField(max_length=13)),
                ('order_list', models.JSONField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('payment', models.BooleanField(default=False)),
                ('random_id', models.CharField(blank=True, max_length=8)),
            ],
        ),
    ]
