# Generated by Django 4.2.14 on 2024-12-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_list',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer_list',
            name='d_callNumber',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='customer_list',
            name='d_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='customer_list',
            name='detail_address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer_list',
            name='memo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customer_list',
            name='zip_code',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
